apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  resources:
    params:
      - name: pathToDockerfile
        type: string
      - name: pathToContext
        type: string
    tasks:
      - name: build-docker-image
        taskRef:
          name: build-docker-image
        params:
          - name: pathToDockerfile
            value: $(resources.params.pathToDockerfile)
          - name: pathToContext
            value: $(resources.params.pathToContext)
